### ISSUE TITLE
support for python<3.8 ?

### ISSUE THREAD

**Issue by dmargala** [minrk/envreport#5]
Hi, I first want to say that this looks like a very helpful tool and captures a lot of things I usually check by hand when debugging environment issue. 

My first attempt to run with the default python3 (Python 3.6) on my system failed with messages like:

```
Traceback (most recent call last):
  File "envreport.py", line 488, in collect
    collector.collect()
  File "envreport.py", line 264, in collect
    out = collect_command_output(command)
  File "envreport.py", line 155, in collect_command_output
    cmd_s = shlex.join(cmd)
AttributeError: module 'shlex' has no attribute 'join'
```

`shlex.join` was added in Python 3.8 though it would probably be pretty straightforward to implement something like it in envreport to support environments with Python<3.8:

https://github.com/python/cpython/blob/39c766b579cabc71a4a50773d299d4350221a70b/Lib/shlex.py#L316-L318

**Comment by minrk** [comment]
ha, I do need to add some tests to make sure it does what it says.

**Comment by dmargala** [comment]
thank you!
